version: "3.8"

services:
  bank-ui:
    container_name: "bank-ui"
     
    image: codewithjass/netbanking_app:bank-ui
    restart: always
    ports:
      - "3003:3003"
    networks:
      - app_network
    env_file:
      - ./dockerEnv/.env.bankUi
    depends_on:
      - bank-server
  bank-client:
    container_name: "bank-client"
     
    image: codewithjass/netbanking_app:bank-client
    # restart: always
    ports:
      - "3005:3005"
    networks:
      - app_network
    env_file:
      - ./dockerEnv/.env.bankClient
    depends_on:
      - bank-server
  transaction-worker:
    container_name: "transaction-worker"
    image: codewithjass/netbanking_app:transaction-worker
    restart: always
    ports:
      - "3006:3006"
 
    networks:
      - app_network
    env_file:
      - ./dockerEnv/.env.transactionWorker
    depends_on:
      - bank-server
      - redis
 

  bank-server:
    container_name: "bank-server"
    image: codewithjass/netbanking_app:bank-server
    restart: always
    ports:
      - "3004:3004"
    
    env_file:
      - ./dockerEnv/.env.bankServer
  
      
      
    depends_on:
      - redis
    networks:
      - app_network
      
  
  redis:
    image: redis:7.2.4
    command: ["redis-server", "--appendonly", "no"]
    restart: always
   
    networks:
      - app_network
    ports: 
      - '6379:6379'
    logging:
      driver: none
    volumes:
      - cache:/data

networks:
  app_network:
    external: true
    driver: bridge
volumes:
  cache:
    driver: local
