name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push BankUi Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./apps/bank-ui/Dockerfile.bankUi
          push: true
          tags: codewithjass/netbanking_app:bank-ui
      - name: Build and Push Transaction-Worker Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./apps/transactionWorker/Dockerfile.transactionWorker
          push: true
          tags: codewithjass/netbanking_app:transaction-worker
      - name: Build and Push Bank-Client Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./apps/bank-client/Dockerfile.bankClient
          push: true
          tags: codewithjass/netbanking_app:bank-client
      - name: Build and Push Bank-Server Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./apps/bank-server/Dockerfile.bankServer
          push: true
          tags: codewithjass/netbanking_app:bank-server

      - name: Verify Pushed Image
        run: docker pull codewithjass/netbanking_app:bank-client
      - name: Verify Pushed Image
        run: docker pull codewithjass/netbanking_app:bank-server
      - name: Verify Pushed Image
        run: docker pull codewithjass/netbanking_app:bank-ui
      - name: Verify Pushed Image
        run: docker pull codewithjass/netbanking_app:transaction-worker

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_NETBANKING_HOST }}
          username: ${{ secrets.SSH_NETBANKING_USERNAME }}
          key: ${{ secrets.SSH_NETBANKING_KEY }}
          script: |
            cd netbankingApp
            sudo docker-compose down
            sudo docker rm -f $(docker ps -a -q) 
            sudo docker rmi -f codewithjass/netbanking_app:transaction-worker || true
            sudo docker rmi -f codewithjass/netbanking_app:bank-ui || true
            sudo docker rmi -f codewithjass/netbanking_app:bank-client || true
            sudo docker rmi -f codewithjass/netbanking_app:bank-server || true
            sudo docker volume rm $(docker volume ls -q)
            sudo docker pull codewithjass/netbanking_app:transaction-worker || true
            sudo docker pull codewithjass/netbanking_app:bank-ui || true
            sudo docker pull codewithjass/netbanking_app:bank-client || true
            sudo docker pull codewithjass/netbanking_app:bank-server || true
            sudo docker network inspect app_network >/dev/null 2>&1 || sudo docker network create app_network

            sudo docker-compose up -d
